name: Dokku
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: Ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Dokku
        uses: marcelinollano/actions/dokku@main
        env:
          BRANCH_FROM: ${{ secrets.BRANCH_FROM }}
          BRANCH_TO: ${{ secrets.BRANCH_TO }}
          DOKKU_APP: ${{ secrets.DOKKU_APP }}
          DOKKU_HOST: ${{ secrets.DOKKU_HOST }}
          DOKKU_PORT: ${{ secrets.DOKKU_PORT }}
          DOKKU_USER: ${{ secrets.DOKKU_USER }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
